#!/usr/bin/env python

"""
Generates random messages in a topic
"""

import rospy
import math
import os
from geometry_msgs.msg import PoseStamped, Point, PoseWithCovarianceStamped
from std_msgs.msg import Int8, String, Bool, Float32, Int8MultiArray
import numpy as np
from borealis_hri_msgs.msg import Borealis_HRI_Output   
import time
import random

rate = 1 # Hz

class message_generator():

    def __init__(self, topic="/HumanPose", type=PoseWithCovarianceStamped, printoutput=True):

        global rate
        self.rosrate=rospy.Rate(rate)

        self.publisher = rospy.Publisher(topic, type,queue_size=1)
        self.message=type()

        while not rospy.is_shutdown():
            
            x = random.randrange(0.9,1.2)
            y = random.randrange(0.9,1.2)
            z = random.randrange(0.9,1.2)
            rx=random.random()
            ry=random.random()
            rz=random.random()
            rw=1

            if type == PoseWithCovarianceStamped:
                msg=PoseWithCovarianceStamped()
                msg.pose.pose.position.x=x
                msg.pose.pose.position.y=y
                msg.pose.pose.position.z=z
                msg.pose.pose.orientation.x=rx
                msg.pose.pose.orientation.y=ry
                msg.pose.pose.orientation.z=rz
                msg.pose.pose.orientation.w=rw
                if printoutput == True: print(msg)
                self.publisher.publish(msg)

            self.rosrate.sleep()





# UAV class to hold variables
class uav():

    def __init__(self):
        self.x=0
        self.y=0
        self.z=0
        self.rx=0
        self.ry=0
        self.rz=0
        self.rw=0


if __name__ == '__main__':
    rospy.init_node('Message_Generator')

    node = message_generator()

    rospy.spin()